
FROM maven:3.9.2-amazoncorretto-20 AS build
COPY src /home/app/src
COPY pom.xml /home/app
ARG AWSURL
ARG AWSUSER
ARG AWSPASSWORD
RUN mvn -f /home/app/pom.xml clean package

FROM maven:3.9.2-amazoncorretto-20
ARG AWSURL
ARG AWSUSER
ARG AWSPASSWORD
COPY --from=build /home/app/target/bookings-0.0.1-SNAPSHOT.jar /usr/local/lib/bookings.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/local/lib/bookings.jar"]